package com.rajan.invoiceflow.workflow;

import com.rajan.invoiceflow.tenant.Tenant;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.util.UUID;

/**
 * Represents an approval workflow definition.
 *
 * A workflow defines how invoices should move through
 * the approval process.
 *
 * Example:
 *
 * Standard Invoice Approval
 *      |
 *      ├── Manager Approval
 *      └── Finance Approval
 *
 * A workflow belongs to one tenant.
 *
 * One tenant can have multiple workflows.
 */
@Entity
@Table(
        name = "approval_workflow",
        uniqueConstraints = {
                /**
                 * Workflow names only need to be unique
                 * within a particular tenant.
                 *
                 * Example:
                 *
                 * Tenant A → Standard Approval     ✅
                 * Tenant B → Standard Approval     ✅
                 * Tenant A → Standard Approval     ❌
                 */
                @UniqueConstraint(
                        name = "uk_workflow_tenant_name",
                        columnNames = {"tenant_id", "name"}
                )
        }
)
public class ApprovalWorkflow {

    /**
     * Primary key of the workflow.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Tenant/company that owns this workflow.
     *
     * This is important for multi-tenancy because
     * workflows must not be shared accidentally between
     * different companies.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "tenant_id", nullable = false)
    private Tenant tenant;

    /**
     * Human-readable name of the workflow.
     *
     * Examples:
     *
     * Standard Invoice Approval
     * High Value Invoice Approval
     * Purchase Invoice Workflow
     */
    @Column(nullable = false, length = 150)
    private String name;

    /**
     * Optional description explaining the purpose
     * or business rules of this workflow.
     */
    @Column(length = 500)
    private String description;

    /**
     * Indicates whether this workflow is currently active.
     *
     * An inactive workflow should not normally be selected
     * for new invoices.
     *
     * We use an active flag instead of deleting old workflows
     * because historical invoices may have used them.
     */
    @Column(nullable = false)
    private boolean active = true;

    /**
     * JPA requires a no-argument constructor.
     *
     * Protected prevents normal application code from
     * accidentally creating an incomplete workflow.
     */
    protected ApprovalWorkflow() {
    }

    /**
     * Creates a new approval workflow.
     *
     * The ID is generated by Hibernate.
     *
     * New workflows are active by default.
     */
    public ApprovalWorkflow(
            Tenant tenant,
            String name,
            String description
    ) {
        this.tenant = tenant;
        this.name = name;
        this.description = description;
        this.active = true;
    }

    // ---------------------------------------------------------
    // Getters
    // ---------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public Tenant getTenant() {
        return tenant;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public boolean isActive() {
        return active;
    }

    // ---------------------------------------------------------
    // Setters
    // ---------------------------------------------------------

    public void setTenant(Tenant tenant) {
        this.tenant = tenant;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
}