package com.rajan.invoiceflow.workflow;

import com.rajan.invoiceflow.role.RoleType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * Represents one approval stage inside an ApprovalWorkflow.
 *
 * Example:
 *
 * ApprovalWorkflow: Standard Invoice Approval
 *
 *     Step 1 → Manager Approval
 *     Step 2 → Finance Approval
 *
 * Each WorkflowStep belongs to exactly one workflow.
 *
 * The stepOrder field determines the sequence in which
 * approval stages are executed.
 *
 * Amount rules allow the workflow engine to later determine
 * whether a particular step applies to an invoice based on
 * its total amount.
 */
@Entity
@Table(
        name = "workflow_step",
        uniqueConstraints = {
                /**
                 * A workflow cannot contain two steps with
                 * the same execution order.
                 *
                 * Example:
                 *
                 * Workflow A:
                 *   Step 1 → Manager
                 *   Step 2 → Finance
                 *
                 * Another Step 2 inside the same workflow
                 * would therefore be invalid.
                 */
                @UniqueConstraint(
                        name = "uk_workflow_step_order",
                        columnNames = {"workflow_id", "step_order"}
                )
        }
)
public class WorkflowStep {

    /**
     * Primary key of the workflow step.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Workflow to which this step belongs.
     *
     * Many WorkflowStep records can belong to one
     * ApprovalWorkflow.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "workflow_id", nullable = false)
    private ApprovalWorkflow workflow;

    /**
     * Determines the order in which this approval step
     * should be executed.
     *
     * Example:
     *
     * 1 → Manager
     * 2 → Finance
     * 3 → Admin
     */
    @Column(name = "step_order", nullable = false)
    private Integer stepOrder;

    /**
     * Human-readable name of the approval stage.
     *
     * Example:
     * "Manager Approval"
     * "Finance Approval"
     */
    @Column(nullable = false, length = 150)
    private String name;

    /**
     * Role responsible for performing this approval step.
     *
     * The role will later be resolved against users belonging
     * to the same tenant.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "required_role", nullable = false, length = 50)
    private RoleType requiredRole;

    /**
     * Minimum invoice amount for which this step applies.
     *
     * Null means there is no minimum amount restriction.
     */
    @Column(name = "min_amount", precision = 19, scale = 2)
    private BigDecimal minAmount;

    /**
     * Maximum invoice amount for which this step applies.
     *
     * Null means there is no maximum amount restriction.
     */
    @Column(name = "max_amount", precision = 19, scale = 2)
    private BigDecimal maxAmount;

    /**
     * Allows a workflow step to be disabled without deleting
     * historical workflow configuration.
     */
    @Column(nullable = false)
    private boolean active = true;

    /**
     * JPA requires a no-argument constructor.
     *
     * Protected prevents normal application code from
     * accidentally creating an incomplete workflow step.
     */
    protected WorkflowStep() {
    }

    /**
     * Creates a new workflow step.
     *
     * The ID is generated by Hibernate.
     *
     * New steps are active by default.
     */
    public WorkflowStep(
            ApprovalWorkflow workflow,
            Integer stepOrder,
            String name,
            RoleType requiredRole,
            BigDecimal minAmount,
            BigDecimal maxAmount
    ) {
        this.workflow = workflow;
        this.stepOrder = stepOrder;
        this.name = name;
        this.requiredRole = requiredRole;
        this.minAmount = minAmount;
        this.maxAmount = maxAmount;
        this.active = true;
    }

    public UUID getId() {
        return id;
    }

    public ApprovalWorkflow getWorkflow() {
        return workflow;
    }

    public Integer getStepOrder() {
        return stepOrder;
    }

    public String getName() {
        return name;
    }

    public RoleType getRequiredRole() {
        return requiredRole;
    }

    public BigDecimal getMinAmount() {
        return minAmount;
    }

    public BigDecimal getMaxAmount() {
        return maxAmount;
    }

    public boolean isActive() {
        return active;
    }

    public void setWorkflow(ApprovalWorkflow workflow) {
        this.workflow = workflow;
    }

    public void setStepOrder(Integer stepOrder) {
        this.stepOrder = stepOrder;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setRequiredRole(RoleType requiredRole) {
        this.requiredRole = requiredRole;
    }

    public void setMinAmount(BigDecimal minAmount) {
        this.minAmount = minAmount;
    }

    public void setMaxAmount(BigDecimal maxAmount) {
        this.maxAmount = maxAmount;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
}